// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/modelmapper/protobuf/pojo/MapMessage.proto

package org.modelmapper.protobuf.pojo;

public final class MapMessageProto {
  private MapMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MapMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.modelmapper.protobuf.pojo.MapMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>map&lt;int32, string&gt; ids = 2;</code>
     */
    int getIdsCount();
    /**
     * <code>map&lt;int32, string&gt; ids = 2;</code>
     */
    boolean containsIds(
        int key);
    /**
     * Use {@link #getIdsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Integer, java.lang.String>
    getIds();
    /**
     * <code>map&lt;int32, string&gt; ids = 2;</code>
     */
    java.util.Map<java.lang.Integer, java.lang.String>
    getIdsMap();
    /**
     * <code>map&lt;int32, string&gt; ids = 2;</code>
     */

    java.lang.String getIdsOrDefault(
        int key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;int32, string&gt; ids = 2;</code>
     */

    java.lang.String getIdsOrThrow(
        int key);
  }
  /**
   * Protobuf type {@code org.modelmapper.protobuf.pojo.MapMessage}
   */
  public static final class MapMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.modelmapper.protobuf.pojo.MapMessage)
      MapMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MapMessage.newBuilder() to construct.
    private MapMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MapMessage() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MapMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MapMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                ids_ = com.google.protobuf.MapField.newMapField(
                    IdsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.Integer, java.lang.String>
              ids__ = input.readMessage(
                  IdsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              ids_.getMutableMap().put(
                  ids__.getKey(), ids__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.modelmapper.protobuf.pojo.MapMessageProto.internal_static_org_modelmapper_protobuf_pojo_MapMessage_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetIds();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.modelmapper.protobuf.pojo.MapMessageProto.internal_static_org_modelmapper_protobuf_pojo_MapMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.modelmapper.protobuf.pojo.MapMessageProto.MapMessage.class, org.modelmapper.protobuf.pojo.MapMessageProto.MapMessage.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IDS_FIELD_NUMBER = 2;
    private static final class IdsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, java.lang.String>newDefaultInstance(
                  org.modelmapper.protobuf.pojo.MapMessageProto.internal_static_org_modelmapper_protobuf_pojo_MapMessage_IdsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.Integer, java.lang.String> ids_;
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.String>
    internalGetIds() {
      if (ids_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            IdsDefaultEntryHolder.defaultEntry);
      }
      return ids_;
    }

    public int getIdsCount() {
      return internalGetIds().getMap().size();
    }
    /**
     * <code>map&lt;int32, string&gt; ids = 2;</code>
     */

    @java.lang.Override
    public boolean containsIds(
        int key) {
      
      return internalGetIds().getMap().containsKey(key);
    }
    /**
     * Use {@link #getIdsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.String> getIds() {
      return getIdsMap();
    }
    /**
     * <code>map&lt;int32, string&gt; ids = 2;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.Integer, java.lang.String> getIdsMap() {
      return internalGetIds().getMap();
    }
    /**
     * <code>map&lt;int32, string&gt; ids = 2;</code>
     */
    @java.lang.Override

    public java.lang.String getIdsOrDefault(
        int key,
        java.lang.String defaultValue) {
      
      java.util.Map<java.lang.Integer, java.lang.String> map =
          internalGetIds().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int32, string&gt; ids = 2;</code>
     */
    @java.lang.Override

    public java.lang.String getIdsOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, java.lang.String> map =
          internalGetIds().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeIntegerMapTo(
          output,
          internalGetIds(),
          IdsDefaultEntryHolder.defaultEntry,
          2);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      for (java.util.Map.Entry<java.lang.Integer, java.lang.String> entry
           : internalGetIds().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, java.lang.String>
        ids__ = IdsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, ids__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.modelmapper.protobuf.pojo.MapMessageProto.MapMessage)) {
        return super.equals(obj);
      }
      org.modelmapper.protobuf.pojo.MapMessageProto.MapMessage other = (org.modelmapper.protobuf.pojo.MapMessageProto.MapMessage) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!internalGetIds().equals(
          other.internalGetIds())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (!internalGetIds().getMap().isEmpty()) {
        hash = (37 * hash) + IDS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetIds().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.modelmapper.protobuf.pojo.MapMessageProto.MapMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.modelmapper.protobuf.pojo.MapMessageProto.MapMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.modelmapper.protobuf.pojo.MapMessageProto.MapMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.modelmapper.protobuf.pojo.MapMessageProto.MapMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.modelmapper.protobuf.pojo.MapMessageProto.MapMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.modelmapper.protobuf.pojo.MapMessageProto.MapMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.modelmapper.protobuf.pojo.MapMessageProto.MapMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.modelmapper.protobuf.pojo.MapMessageProto.MapMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.modelmapper.protobuf.pojo.MapMessageProto.MapMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.modelmapper.protobuf.pojo.MapMessageProto.MapMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.modelmapper.protobuf.pojo.MapMessageProto.MapMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.modelmapper.protobuf.pojo.MapMessageProto.MapMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.modelmapper.protobuf.pojo.MapMessageProto.MapMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.modelmapper.protobuf.pojo.MapMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.modelmapper.protobuf.pojo.MapMessage)
        org.modelmapper.protobuf.pojo.MapMessageProto.MapMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.modelmapper.protobuf.pojo.MapMessageProto.internal_static_org_modelmapper_protobuf_pojo_MapMessage_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetIds();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetMutableIds();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.modelmapper.protobuf.pojo.MapMessageProto.internal_static_org_modelmapper_protobuf_pojo_MapMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.modelmapper.protobuf.pojo.MapMessageProto.MapMessage.class, org.modelmapper.protobuf.pojo.MapMessageProto.MapMessage.Builder.class);
      }

      // Construct using org.modelmapper.protobuf.pojo.MapMessageProto.MapMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        internalGetMutableIds().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.modelmapper.protobuf.pojo.MapMessageProto.internal_static_org_modelmapper_protobuf_pojo_MapMessage_descriptor;
      }

      @java.lang.Override
      public org.modelmapper.protobuf.pojo.MapMessageProto.MapMessage getDefaultInstanceForType() {
        return org.modelmapper.protobuf.pojo.MapMessageProto.MapMessage.getDefaultInstance();
      }

      @java.lang.Override
      public org.modelmapper.protobuf.pojo.MapMessageProto.MapMessage build() {
        org.modelmapper.protobuf.pojo.MapMessageProto.MapMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.modelmapper.protobuf.pojo.MapMessageProto.MapMessage buildPartial() {
        org.modelmapper.protobuf.pojo.MapMessageProto.MapMessage result = new org.modelmapper.protobuf.pojo.MapMessageProto.MapMessage(this);
        int from_bitField0_ = bitField0_;
        result.name_ = name_;
        result.ids_ = internalGetIds();
        result.ids_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.modelmapper.protobuf.pojo.MapMessageProto.MapMessage) {
          return mergeFrom((org.modelmapper.protobuf.pojo.MapMessageProto.MapMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.modelmapper.protobuf.pojo.MapMessageProto.MapMessage other) {
        if (other == org.modelmapper.protobuf.pojo.MapMessageProto.MapMessage.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        internalGetMutableIds().mergeFrom(
            other.internalGetIds());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.modelmapper.protobuf.pojo.MapMessageProto.MapMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.modelmapper.protobuf.pojo.MapMessageProto.MapMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.Integer, java.lang.String> ids_;
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.String>
      internalGetIds() {
        if (ids_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              IdsDefaultEntryHolder.defaultEntry);
        }
        return ids_;
      }
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.String>
      internalGetMutableIds() {
        onChanged();;
        if (ids_ == null) {
          ids_ = com.google.protobuf.MapField.newMapField(
              IdsDefaultEntryHolder.defaultEntry);
        }
        if (!ids_.isMutable()) {
          ids_ = ids_.copy();
        }
        return ids_;
      }

      public int getIdsCount() {
        return internalGetIds().getMap().size();
      }
      /**
       * <code>map&lt;int32, string&gt; ids = 2;</code>
       */

      @java.lang.Override
      public boolean containsIds(
          int key) {
        
        return internalGetIds().getMap().containsKey(key);
      }
      /**
       * Use {@link #getIdsMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, java.lang.String> getIds() {
        return getIdsMap();
      }
      /**
       * <code>map&lt;int32, string&gt; ids = 2;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.Integer, java.lang.String> getIdsMap() {
        return internalGetIds().getMap();
      }
      /**
       * <code>map&lt;int32, string&gt; ids = 2;</code>
       */
      @java.lang.Override

      public java.lang.String getIdsOrDefault(
          int key,
          java.lang.String defaultValue) {
        
        java.util.Map<java.lang.Integer, java.lang.String> map =
            internalGetIds().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;int32, string&gt; ids = 2;</code>
       */
      @java.lang.Override

      public java.lang.String getIdsOrThrow(
          int key) {
        
        java.util.Map<java.lang.Integer, java.lang.String> map =
            internalGetIds().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearIds() {
        internalGetMutableIds().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;int32, string&gt; ids = 2;</code>
       */

      public Builder removeIds(
          int key) {
        
        internalGetMutableIds().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, java.lang.String>
      getMutableIds() {
        return internalGetMutableIds().getMutableMap();
      }
      /**
       * <code>map&lt;int32, string&gt; ids = 2;</code>
       */
      public Builder putIds(
          int key,
          java.lang.String value) {
        
        if (value == null) {
  throw new NullPointerException("map value");
}

        internalGetMutableIds().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;int32, string&gt; ids = 2;</code>
       */

      public Builder putAllIds(
          java.util.Map<java.lang.Integer, java.lang.String> values) {
        internalGetMutableIds().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.modelmapper.protobuf.pojo.MapMessage)
    }

    // @@protoc_insertion_point(class_scope:org.modelmapper.protobuf.pojo.MapMessage)
    private static final org.modelmapper.protobuf.pojo.MapMessageProto.MapMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.modelmapper.protobuf.pojo.MapMessageProto.MapMessage();
    }

    public static org.modelmapper.protobuf.pojo.MapMessageProto.MapMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MapMessage>
        PARSER = new com.google.protobuf.AbstractParser<MapMessage>() {
      @java.lang.Override
      public MapMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MapMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MapMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MapMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.modelmapper.protobuf.pojo.MapMessageProto.MapMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_modelmapper_protobuf_pojo_MapMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_modelmapper_protobuf_pojo_MapMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_modelmapper_protobuf_pojo_MapMessage_IdsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_modelmapper_protobuf_pojo_MapMessage_IdsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n.org/modelmapper/protobuf/pojo/MapMessa" +
      "ge.proto\022\035org.modelmapper.protobuf.pojo\"" +
      "\207\001\n\nMapMessage\022\014\n\004name\030\001 \001(\t\022?\n\003ids\030\002 \003(" +
      "\01322.org.modelmapper.protobuf.pojo.MapMes" +
      "sage.IdsEntry\032*\n\010IdsEntry\022\013\n\003key\030\001 \001(\005\022\r" +
      "\n\005value\030\002 \001(\t:\0028\001B0\n\035org.modelmapper.pro" +
      "tobuf.pojoB\017MapMessageProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_modelmapper_protobuf_pojo_MapMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_modelmapper_protobuf_pojo_MapMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_modelmapper_protobuf_pojo_MapMessage_descriptor,
        new java.lang.String[] { "Name", "Ids", });
    internal_static_org_modelmapper_protobuf_pojo_MapMessage_IdsEntry_descriptor =
      internal_static_org_modelmapper_protobuf_pojo_MapMessage_descriptor.getNestedTypes().get(0);
    internal_static_org_modelmapper_protobuf_pojo_MapMessage_IdsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_modelmapper_protobuf_pojo_MapMessage_IdsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
