// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/modelmapper/protobuf/pojo/TestMessage.proto

package org.modelmapper.protobuf.pojo;

public final class TestMessageProto {
  private TestMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TestMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.hashdata.cloudmgr.account.TestMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.google.protobuf.StringValue message_content = 1;</code>
     */
    boolean hasMessageContent();
    /**
     * <code>.google.protobuf.StringValue message_content = 1;</code>
     */
    com.google.protobuf.StringValue getMessageContent();
    /**
     * <code>.google.protobuf.StringValue message_content = 1;</code>
     */
    com.google.protobuf.StringValueOrBuilder getMessageContentOrBuilder();
  }
  /**
   * Protobuf type {@code cn.hashdata.cloudmgr.account.TestMessage}
   */
  public  static final class TestMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.hashdata.cloudmgr.account.TestMessage)
      TestMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TestMessage.newBuilder() to construct.
    private TestMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TestMessage() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TestMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.StringValue.Builder subBuilder = null;
              if (messageContent_ != null) {
                subBuilder = messageContent_.toBuilder();
              }
              messageContent_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(messageContent_);
                messageContent_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.modelmapper.protobuf.pojo.TestMessageProto.internal_static_cn_hashdata_cloudmgr_account_TestMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.modelmapper.protobuf.pojo.TestMessageProto.internal_static_cn_hashdata_cloudmgr_account_TestMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.modelmapper.protobuf.pojo.TestMessageProto.TestMessage.class, org.modelmapper.protobuf.pojo.TestMessageProto.TestMessage.Builder.class);
    }

    public static final int MESSAGE_CONTENT_FIELD_NUMBER = 1;
    private com.google.protobuf.StringValue messageContent_;
    /**
     * <code>.google.protobuf.StringValue message_content = 1;</code>
     */
    public boolean hasMessageContent() {
      return messageContent_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue message_content = 1;</code>
     */
    public com.google.protobuf.StringValue getMessageContent() {
      return messageContent_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : messageContent_;
    }
    /**
     * <code>.google.protobuf.StringValue message_content = 1;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getMessageContentOrBuilder() {
      return getMessageContent();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (messageContent_ != null) {
        output.writeMessage(1, getMessageContent());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (messageContent_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMessageContent());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.modelmapper.protobuf.pojo.TestMessageProto.TestMessage)) {
        return super.equals(obj);
      }
      org.modelmapper.protobuf.pojo.TestMessageProto.TestMessage other = (org.modelmapper.protobuf.pojo.TestMessageProto.TestMessage) obj;

      if (hasMessageContent() != other.hasMessageContent()) return false;
      if (hasMessageContent()) {
        if (!getMessageContent()
            .equals(other.getMessageContent())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMessageContent()) {
        hash = (37 * hash) + MESSAGE_CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getMessageContent().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.modelmapper.protobuf.pojo.TestMessageProto.TestMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.modelmapper.protobuf.pojo.TestMessageProto.TestMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.modelmapper.protobuf.pojo.TestMessageProto.TestMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.modelmapper.protobuf.pojo.TestMessageProto.TestMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.modelmapper.protobuf.pojo.TestMessageProto.TestMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.modelmapper.protobuf.pojo.TestMessageProto.TestMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.modelmapper.protobuf.pojo.TestMessageProto.TestMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.modelmapper.protobuf.pojo.TestMessageProto.TestMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.modelmapper.protobuf.pojo.TestMessageProto.TestMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.modelmapper.protobuf.pojo.TestMessageProto.TestMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.modelmapper.protobuf.pojo.TestMessageProto.TestMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.modelmapper.protobuf.pojo.TestMessageProto.TestMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.modelmapper.protobuf.pojo.TestMessageProto.TestMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.hashdata.cloudmgr.account.TestMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.hashdata.cloudmgr.account.TestMessage)
        org.modelmapper.protobuf.pojo.TestMessageProto.TestMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.modelmapper.protobuf.pojo.TestMessageProto.internal_static_cn_hashdata_cloudmgr_account_TestMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.modelmapper.protobuf.pojo.TestMessageProto.internal_static_cn_hashdata_cloudmgr_account_TestMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.modelmapper.protobuf.pojo.TestMessageProto.TestMessage.class, org.modelmapper.protobuf.pojo.TestMessageProto.TestMessage.Builder.class);
      }

      // Construct using org.modelmapper.protobuf.pojo.TestMessageProto.TestMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (messageContentBuilder_ == null) {
          messageContent_ = null;
        } else {
          messageContent_ = null;
          messageContentBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.modelmapper.protobuf.pojo.TestMessageProto.internal_static_cn_hashdata_cloudmgr_account_TestMessage_descriptor;
      }

      @java.lang.Override
      public org.modelmapper.protobuf.pojo.TestMessageProto.TestMessage getDefaultInstanceForType() {
        return org.modelmapper.protobuf.pojo.TestMessageProto.TestMessage.getDefaultInstance();
      }

      @java.lang.Override
      public org.modelmapper.protobuf.pojo.TestMessageProto.TestMessage build() {
        org.modelmapper.protobuf.pojo.TestMessageProto.TestMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.modelmapper.protobuf.pojo.TestMessageProto.TestMessage buildPartial() {
        org.modelmapper.protobuf.pojo.TestMessageProto.TestMessage result = new org.modelmapper.protobuf.pojo.TestMessageProto.TestMessage(this);
        if (messageContentBuilder_ == null) {
          result.messageContent_ = messageContent_;
        } else {
          result.messageContent_ = messageContentBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.modelmapper.protobuf.pojo.TestMessageProto.TestMessage) {
          return mergeFrom((org.modelmapper.protobuf.pojo.TestMessageProto.TestMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.modelmapper.protobuf.pojo.TestMessageProto.TestMessage other) {
        if (other == org.modelmapper.protobuf.pojo.TestMessageProto.TestMessage.getDefaultInstance()) return this;
        if (other.hasMessageContent()) {
          mergeMessageContent(other.getMessageContent());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.modelmapper.protobuf.pojo.TestMessageProto.TestMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.modelmapper.protobuf.pojo.TestMessageProto.TestMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.StringValue messageContent_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> messageContentBuilder_;
      /**
       * <code>.google.protobuf.StringValue message_content = 1;</code>
       */
      public boolean hasMessageContent() {
        return messageContentBuilder_ != null || messageContent_ != null;
      }
      /**
       * <code>.google.protobuf.StringValue message_content = 1;</code>
       */
      public com.google.protobuf.StringValue getMessageContent() {
        if (messageContentBuilder_ == null) {
          return messageContent_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : messageContent_;
        } else {
          return messageContentBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.StringValue message_content = 1;</code>
       */
      public Builder setMessageContent(com.google.protobuf.StringValue value) {
        if (messageContentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          messageContent_ = value;
          onChanged();
        } else {
          messageContentBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue message_content = 1;</code>
       */
      public Builder setMessageContent(
          com.google.protobuf.StringValue.Builder builderForValue) {
        if (messageContentBuilder_ == null) {
          messageContent_ = builderForValue.build();
          onChanged();
        } else {
          messageContentBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue message_content = 1;</code>
       */
      public Builder mergeMessageContent(com.google.protobuf.StringValue value) {
        if (messageContentBuilder_ == null) {
          if (messageContent_ != null) {
            messageContent_ =
              com.google.protobuf.StringValue.newBuilder(messageContent_).mergeFrom(value).buildPartial();
          } else {
            messageContent_ = value;
          }
          onChanged();
        } else {
          messageContentBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue message_content = 1;</code>
       */
      public Builder clearMessageContent() {
        if (messageContentBuilder_ == null) {
          messageContent_ = null;
          onChanged();
        } else {
          messageContent_ = null;
          messageContentBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue message_content = 1;</code>
       */
      public com.google.protobuf.StringValue.Builder getMessageContentBuilder() {
        
        onChanged();
        return getMessageContentFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.StringValue message_content = 1;</code>
       */
      public com.google.protobuf.StringValueOrBuilder getMessageContentOrBuilder() {
        if (messageContentBuilder_ != null) {
          return messageContentBuilder_.getMessageOrBuilder();
        } else {
          return messageContent_ == null ?
              com.google.protobuf.StringValue.getDefaultInstance() : messageContent_;
        }
      }
      /**
       * <code>.google.protobuf.StringValue message_content = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
          getMessageContentFieldBuilder() {
        if (messageContentBuilder_ == null) {
          messageContentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                  getMessageContent(),
                  getParentForChildren(),
                  isClean());
          messageContent_ = null;
        }
        return messageContentBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.hashdata.cloudmgr.account.TestMessage)
    }

    // @@protoc_insertion_point(class_scope:cn.hashdata.cloudmgr.account.TestMessage)
    private static final org.modelmapper.protobuf.pojo.TestMessageProto.TestMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.modelmapper.protobuf.pojo.TestMessageProto.TestMessage();
    }

    public static org.modelmapper.protobuf.pojo.TestMessageProto.TestMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TestMessage>
        PARSER = new com.google.protobuf.AbstractParser<TestMessage>() {
      @java.lang.Override
      public TestMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TestMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TestMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TestMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.modelmapper.protobuf.pojo.TestMessageProto.TestMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_hashdata_cloudmgr_account_TestMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_hashdata_cloudmgr_account_TestMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n/org/modelmapper/protobuf/pojo/TestMess" +
      "age.proto\022\034cn.hashdata.cloudmgr.account\032" +
      "\036google/protobuf/wrappers.proto\"D\n\013TestM" +
      "essage\0225\n\017message_content\030\001 \001(\0132\034.google" +
      ".protobuf.StringValueB3\n\035org.modelmapper" +
      ".protobuf.pojoB\020TestMessageProtoP\000b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
        }, assigner);
    internal_static_cn_hashdata_cloudmgr_account_TestMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_hashdata_cloudmgr_account_TestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_hashdata_cloudmgr_account_TestMessage_descriptor,
        new java.lang.String[] { "MessageContent", });
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
