language: java
sudo: required
cache:
  directories:
  - $HOME/.m2
dist: trusty

jdk:
  - openjdk7
  - oraclejdk8
  - oraclejdk9
  - openjdk11

notifications:
  email: false

# whitelist
branches:
  only:
    - master

sudo: false
