// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gh265.proto

package org.modelmapper.protobuf.gh392;

public final class DestinationInstructionProto {
  private DestinationInstructionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DestinationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:demo.Destination)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string type = 1;</code>
     */
    java.lang.String getType();
    /**
     * <code>string type = 1;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>repeated .demo.Element1 e1 = 2;</code>
     */
    java.util.List<org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1> 
        getE1List();
    /**
     * <code>repeated .demo.Element1 e1 = 2;</code>
     */
    org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1 getE1(int index);
    /**
     * <code>repeated .demo.Element1 e1 = 2;</code>
     */
    int getE1Count();
    /**
     * <code>repeated .demo.Element1 e1 = 2;</code>
     */
    java.util.List<? extends org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1OrBuilder> 
        getE1OrBuilderList();
    /**
     * <code>repeated .demo.Element1 e1 = 2;</code>
     */
    org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1OrBuilder getE1OrBuilder(
        int index);

    /**
     * <code>string status = 3;</code>
     */
    java.lang.String getStatus();
    /**
     * <code>string status = 3;</code>
     */
    com.google.protobuf.ByteString
        getStatusBytes();
  }
  /**
   * Protobuf type {@code demo.Destination}
   */
  public  static final class Destination extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:demo.Destination)
      DestinationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Destination.newBuilder() to construct.
    private Destination(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Destination() {
      type_ = "";
      e1_ = java.util.Collections.emptyList();
      status_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Destination(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                e1_ = new java.util.ArrayList<org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1>();
                mutable_bitField0_ |= 0x00000002;
              }
              e1_.add(
                  input.readMessage(org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1.parser(), extensionRegistry));
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              status_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          e1_ = java.util.Collections.unmodifiableList(e1_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.modelmapper.protobuf.gh392.DestinationInstructionProto.internal_static_demo_Destination_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.modelmapper.protobuf.gh392.DestinationInstructionProto.internal_static_demo_Destination_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.modelmapper.protobuf.gh392.DestinationInstructionProto.Destination.class, org.modelmapper.protobuf.gh392.DestinationInstructionProto.Destination.Builder.class);
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object type_;
    /**
     * <code>string type = 1;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <code>string type = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int E1_FIELD_NUMBER = 2;
    private java.util.List<org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1> e1_;
    /**
     * <code>repeated .demo.Element1 e1 = 2;</code>
     */
    public java.util.List<org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1> getE1List() {
      return e1_;
    }
    /**
     * <code>repeated .demo.Element1 e1 = 2;</code>
     */
    public java.util.List<? extends org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1OrBuilder> 
        getE1OrBuilderList() {
      return e1_;
    }
    /**
     * <code>repeated .demo.Element1 e1 = 2;</code>
     */
    public int getE1Count() {
      return e1_.size();
    }
    /**
     * <code>repeated .demo.Element1 e1 = 2;</code>
     */
    public org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1 getE1(int index) {
      return e1_.get(index);
    }
    /**
     * <code>repeated .demo.Element1 e1 = 2;</code>
     */
    public org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1OrBuilder getE1OrBuilder(
        int index) {
      return e1_.get(index);
    }

    public static final int STATUS_FIELD_NUMBER = 3;
    private volatile java.lang.Object status_;
    /**
     * <code>string status = 3;</code>
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      }
    }
    /**
     * <code>string status = 3;</code>
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
      }
      for (int i = 0; i < e1_.size(); i++) {
        output.writeMessage(2, e1_.get(i));
      }
      if (!getStatusBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, status_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
      }
      for (int i = 0; i < e1_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, e1_.get(i));
      }
      if (!getStatusBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, status_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.modelmapper.protobuf.gh392.DestinationInstructionProto.Destination)) {
        return super.equals(obj);
      }
      org.modelmapper.protobuf.gh392.DestinationInstructionProto.Destination other = (org.modelmapper.protobuf.gh392.DestinationInstructionProto.Destination) obj;

      boolean result = true;
      result = result && getType()
          .equals(other.getType());
      result = result && getE1List()
          .equals(other.getE1List());
      result = result && getStatus()
          .equals(other.getStatus());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      if (getE1Count() > 0) {
        hash = (37 * hash) + E1_FIELD_NUMBER;
        hash = (53 * hash) + getE1List().hashCode();
      }
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.modelmapper.protobuf.gh392.DestinationInstructionProto.Destination parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.modelmapper.protobuf.gh392.DestinationInstructionProto.Destination parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.modelmapper.protobuf.gh392.DestinationInstructionProto.Destination parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.modelmapper.protobuf.gh392.DestinationInstructionProto.Destination parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.modelmapper.protobuf.gh392.DestinationInstructionProto.Destination parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.modelmapper.protobuf.gh392.DestinationInstructionProto.Destination parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.modelmapper.protobuf.gh392.DestinationInstructionProto.Destination parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.modelmapper.protobuf.gh392.DestinationInstructionProto.Destination parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.modelmapper.protobuf.gh392.DestinationInstructionProto.Destination parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.modelmapper.protobuf.gh392.DestinationInstructionProto.Destination parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.modelmapper.protobuf.gh392.DestinationInstructionProto.Destination parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.modelmapper.protobuf.gh392.DestinationInstructionProto.Destination parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.modelmapper.protobuf.gh392.DestinationInstructionProto.Destination prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code demo.Destination}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:demo.Destination)
        org.modelmapper.protobuf.gh392.DestinationInstructionProto.DestinationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.modelmapper.protobuf.gh392.DestinationInstructionProto.internal_static_demo_Destination_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.modelmapper.protobuf.gh392.DestinationInstructionProto.internal_static_demo_Destination_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.modelmapper.protobuf.gh392.DestinationInstructionProto.Destination.class, org.modelmapper.protobuf.gh392.DestinationInstructionProto.Destination.Builder.class);
      }

      // Construct using org.modelmapper.protobuf.gh392.DestinationInstructionProto.Destination.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getE1FieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        type_ = "";

        if (e1Builder_ == null) {
          e1_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          e1Builder_.clear();
        }
        status_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.modelmapper.protobuf.gh392.DestinationInstructionProto.internal_static_demo_Destination_descriptor;
      }

      public org.modelmapper.protobuf.gh392.DestinationInstructionProto.Destination getDefaultInstanceForType() {
        return org.modelmapper.protobuf.gh392.DestinationInstructionProto.Destination.getDefaultInstance();
      }

      public org.modelmapper.protobuf.gh392.DestinationInstructionProto.Destination build() {
        org.modelmapper.protobuf.gh392.DestinationInstructionProto.Destination result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.modelmapper.protobuf.gh392.DestinationInstructionProto.Destination buildPartial() {
        org.modelmapper.protobuf.gh392.DestinationInstructionProto.Destination result = new org.modelmapper.protobuf.gh392.DestinationInstructionProto.Destination(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.type_ = type_;
        if (e1Builder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            e1_ = java.util.Collections.unmodifiableList(e1_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.e1_ = e1_;
        } else {
          result.e1_ = e1Builder_.build();
        }
        result.status_ = status_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.modelmapper.protobuf.gh392.DestinationInstructionProto.Destination) {
          return mergeFrom((org.modelmapper.protobuf.gh392.DestinationInstructionProto.Destination)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.modelmapper.protobuf.gh392.DestinationInstructionProto.Destination other) {
        if (other == org.modelmapper.protobuf.gh392.DestinationInstructionProto.Destination.getDefaultInstance()) return this;
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        if (e1Builder_ == null) {
          if (!other.e1_.isEmpty()) {
            if (e1_.isEmpty()) {
              e1_ = other.e1_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureE1IsMutable();
              e1_.addAll(other.e1_);
            }
            onChanged();
          }
        } else {
          if (!other.e1_.isEmpty()) {
            if (e1Builder_.isEmpty()) {
              e1Builder_.dispose();
              e1Builder_ = null;
              e1_ = other.e1_;
              bitField0_ = (bitField0_ & ~0x00000002);
              e1Builder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getE1FieldBuilder() : null;
            } else {
              e1Builder_.addAllMessages(other.e1_);
            }
          }
        }
        if (!other.getStatus().isEmpty()) {
          status_ = other.status_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.modelmapper.protobuf.gh392.DestinationInstructionProto.Destination parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.modelmapper.protobuf.gh392.DestinationInstructionProto.Destination) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object type_ = "";
      /**
       * <code>string type = 1;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string type = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string type = 1;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>string type = 1;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        type_ = value;
        onChanged();
        return this;
      }

      private java.util.List<org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1> e1_ =
        java.util.Collections.emptyList();
      private void ensureE1IsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          e1_ = new java.util.ArrayList<org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1>(e1_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1, org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1.Builder, org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1OrBuilder> e1Builder_;

      /**
       * <code>repeated .demo.Element1 e1 = 2;</code>
       */
      public java.util.List<org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1> getE1List() {
        if (e1Builder_ == null) {
          return java.util.Collections.unmodifiableList(e1_);
        } else {
          return e1Builder_.getMessageList();
        }
      }
      /**
       * <code>repeated .demo.Element1 e1 = 2;</code>
       */
      public int getE1Count() {
        if (e1Builder_ == null) {
          return e1_.size();
        } else {
          return e1Builder_.getCount();
        }
      }
      /**
       * <code>repeated .demo.Element1 e1 = 2;</code>
       */
      public org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1 getE1(int index) {
        if (e1Builder_ == null) {
          return e1_.get(index);
        } else {
          return e1Builder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .demo.Element1 e1 = 2;</code>
       */
      public Builder setE1(
          int index, org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1 value) {
        if (e1Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureE1IsMutable();
          e1_.set(index, value);
          onChanged();
        } else {
          e1Builder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .demo.Element1 e1 = 2;</code>
       */
      public Builder setE1(
          int index, org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1.Builder builderForValue) {
        if (e1Builder_ == null) {
          ensureE1IsMutable();
          e1_.set(index, builderForValue.build());
          onChanged();
        } else {
          e1Builder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .demo.Element1 e1 = 2;</code>
       */
      public Builder addE1(org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1 value) {
        if (e1Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureE1IsMutable();
          e1_.add(value);
          onChanged();
        } else {
          e1Builder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .demo.Element1 e1 = 2;</code>
       */
      public Builder addE1(
          int index, org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1 value) {
        if (e1Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureE1IsMutable();
          e1_.add(index, value);
          onChanged();
        } else {
          e1Builder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .demo.Element1 e1 = 2;</code>
       */
      public Builder addE1(
          org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1.Builder builderForValue) {
        if (e1Builder_ == null) {
          ensureE1IsMutable();
          e1_.add(builderForValue.build());
          onChanged();
        } else {
          e1Builder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .demo.Element1 e1 = 2;</code>
       */
      public Builder addE1(
          int index, org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1.Builder builderForValue) {
        if (e1Builder_ == null) {
          ensureE1IsMutable();
          e1_.add(index, builderForValue.build());
          onChanged();
        } else {
          e1Builder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .demo.Element1 e1 = 2;</code>
       */
      public Builder addAllE1(
          java.lang.Iterable<? extends org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1> values) {
        if (e1Builder_ == null) {
          ensureE1IsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, e1_);
          onChanged();
        } else {
          e1Builder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .demo.Element1 e1 = 2;</code>
       */
      public Builder clearE1() {
        if (e1Builder_ == null) {
          e1_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          e1Builder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .demo.Element1 e1 = 2;</code>
       */
      public Builder removeE1(int index) {
        if (e1Builder_ == null) {
          ensureE1IsMutable();
          e1_.remove(index);
          onChanged();
        } else {
          e1Builder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .demo.Element1 e1 = 2;</code>
       */
      public org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1.Builder getE1Builder(
          int index) {
        return getE1FieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .demo.Element1 e1 = 2;</code>
       */
      public org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1OrBuilder getE1OrBuilder(
          int index) {
        if (e1Builder_ == null) {
          return e1_.get(index);  } else {
          return e1Builder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .demo.Element1 e1 = 2;</code>
       */
      public java.util.List<? extends org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1OrBuilder> 
           getE1OrBuilderList() {
        if (e1Builder_ != null) {
          return e1Builder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(e1_);
        }
      }
      /**
       * <code>repeated .demo.Element1 e1 = 2;</code>
       */
      public org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1.Builder addE1Builder() {
        return getE1FieldBuilder().addBuilder(
            org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1.getDefaultInstance());
      }
      /**
       * <code>repeated .demo.Element1 e1 = 2;</code>
       */
      public org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1.Builder addE1Builder(
          int index) {
        return getE1FieldBuilder().addBuilder(
            index, org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1.getDefaultInstance());
      }
      /**
       * <code>repeated .demo.Element1 e1 = 2;</code>
       */
      public java.util.List<org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1.Builder> 
           getE1BuilderList() {
        return getE1FieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1, org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1.Builder, org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1OrBuilder> 
          getE1FieldBuilder() {
        if (e1Builder_ == null) {
          e1Builder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1, org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1.Builder, org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1OrBuilder>(
                  e1_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          e1_ = null;
        }
        return e1Builder_;
      }

      private java.lang.Object status_ = "";
      /**
       * <code>string status = 3;</code>
       */
      public java.lang.String getStatus() {
        java.lang.Object ref = status_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          status_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string status = 3;</code>
       */
      public com.google.protobuf.ByteString
          getStatusBytes() {
        java.lang.Object ref = status_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          status_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string status = 3;</code>
       */
      public Builder setStatus(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string status = 3;</code>
       */
      public Builder clearStatus() {
        
        status_ = getDefaultInstance().getStatus();
        onChanged();
        return this;
      }
      /**
       * <code>string status = 3;</code>
       */
      public Builder setStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        status_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:demo.Destination)
    }

    // @@protoc_insertion_point(class_scope:demo.Destination)
    private static final org.modelmapper.protobuf.gh392.DestinationInstructionProto.Destination DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.modelmapper.protobuf.gh392.DestinationInstructionProto.Destination();
    }

    public static org.modelmapper.protobuf.gh392.DestinationInstructionProto.Destination getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Destination>
        PARSER = new com.google.protobuf.AbstractParser<Destination>() {
      public Destination parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Destination(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Destination> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Destination> getParserForType() {
      return PARSER;
    }

    public org.modelmapper.protobuf.gh392.DestinationInstructionProto.Destination getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface Element1OrBuilder extends
      // @@protoc_insertion_point(interface_extends:demo.Element1)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .demo.Element2 e2 = 2;</code>
     */
    java.util.List<org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2> 
        getE2List();
    /**
     * <code>repeated .demo.Element2 e2 = 2;</code>
     */
    org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2 getE2(int index);
    /**
     * <code>repeated .demo.Element2 e2 = 2;</code>
     */
    int getE2Count();
    /**
     * <code>repeated .demo.Element2 e2 = 2;</code>
     */
    java.util.List<? extends org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2OrBuilder> 
        getE2OrBuilderList();
    /**
     * <code>repeated .demo.Element2 e2 = 2;</code>
     */
    org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2OrBuilder getE2OrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code demo.Element1}
   */
  public  static final class Element1 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:demo.Element1)
      Element1OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Element1.newBuilder() to construct.
    private Element1(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Element1() {
      e2_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Element1(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                e2_ = new java.util.ArrayList<org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2>();
                mutable_bitField0_ |= 0x00000001;
              }
              e2_.add(
                  input.readMessage(org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          e2_ = java.util.Collections.unmodifiableList(e2_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.modelmapper.protobuf.gh392.DestinationInstructionProto.internal_static_demo_Element1_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.modelmapper.protobuf.gh392.DestinationInstructionProto.internal_static_demo_Element1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1.class, org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1.Builder.class);
    }

    public static final int E2_FIELD_NUMBER = 2;
    private java.util.List<org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2> e2_;
    /**
     * <code>repeated .demo.Element2 e2 = 2;</code>
     */
    public java.util.List<org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2> getE2List() {
      return e2_;
    }
    /**
     * <code>repeated .demo.Element2 e2 = 2;</code>
     */
    public java.util.List<? extends org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2OrBuilder> 
        getE2OrBuilderList() {
      return e2_;
    }
    /**
     * <code>repeated .demo.Element2 e2 = 2;</code>
     */
    public int getE2Count() {
      return e2_.size();
    }
    /**
     * <code>repeated .demo.Element2 e2 = 2;</code>
     */
    public org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2 getE2(int index) {
      return e2_.get(index);
    }
    /**
     * <code>repeated .demo.Element2 e2 = 2;</code>
     */
    public org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2OrBuilder getE2OrBuilder(
        int index) {
      return e2_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < e2_.size(); i++) {
        output.writeMessage(2, e2_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < e2_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, e2_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1)) {
        return super.equals(obj);
      }
      org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1 other = (org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1) obj;

      boolean result = true;
      result = result && getE2List()
          .equals(other.getE2List());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getE2Count() > 0) {
        hash = (37 * hash) + E2_FIELD_NUMBER;
        hash = (53 * hash) + getE2List().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code demo.Element1}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:demo.Element1)
        org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.modelmapper.protobuf.gh392.DestinationInstructionProto.internal_static_demo_Element1_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.modelmapper.protobuf.gh392.DestinationInstructionProto.internal_static_demo_Element1_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1.class, org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1.Builder.class);
      }

      // Construct using org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getE2FieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (e2Builder_ == null) {
          e2_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          e2Builder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.modelmapper.protobuf.gh392.DestinationInstructionProto.internal_static_demo_Element1_descriptor;
      }

      public org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1 getDefaultInstanceForType() {
        return org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1.getDefaultInstance();
      }

      public org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1 build() {
        org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1 buildPartial() {
        org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1 result = new org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1(this);
        int from_bitField0_ = bitField0_;
        if (e2Builder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            e2_ = java.util.Collections.unmodifiableList(e2_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.e2_ = e2_;
        } else {
          result.e2_ = e2Builder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1) {
          return mergeFrom((org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1 other) {
        if (other == org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1.getDefaultInstance()) return this;
        if (e2Builder_ == null) {
          if (!other.e2_.isEmpty()) {
            if (e2_.isEmpty()) {
              e2_ = other.e2_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureE2IsMutable();
              e2_.addAll(other.e2_);
            }
            onChanged();
          }
        } else {
          if (!other.e2_.isEmpty()) {
            if (e2Builder_.isEmpty()) {
              e2Builder_.dispose();
              e2Builder_ = null;
              e2_ = other.e2_;
              bitField0_ = (bitField0_ & ~0x00000001);
              e2Builder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getE2FieldBuilder() : null;
            } else {
              e2Builder_.addAllMessages(other.e2_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2> e2_ =
        java.util.Collections.emptyList();
      private void ensureE2IsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          e2_ = new java.util.ArrayList<org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2>(e2_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2, org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2.Builder, org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2OrBuilder> e2Builder_;

      /**
       * <code>repeated .demo.Element2 e2 = 2;</code>
       */
      public java.util.List<org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2> getE2List() {
        if (e2Builder_ == null) {
          return java.util.Collections.unmodifiableList(e2_);
        } else {
          return e2Builder_.getMessageList();
        }
      }
      /**
       * <code>repeated .demo.Element2 e2 = 2;</code>
       */
      public int getE2Count() {
        if (e2Builder_ == null) {
          return e2_.size();
        } else {
          return e2Builder_.getCount();
        }
      }
      /**
       * <code>repeated .demo.Element2 e2 = 2;</code>
       */
      public org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2 getE2(int index) {
        if (e2Builder_ == null) {
          return e2_.get(index);
        } else {
          return e2Builder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .demo.Element2 e2 = 2;</code>
       */
      public Builder setE2(
          int index, org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2 value) {
        if (e2Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureE2IsMutable();
          e2_.set(index, value);
          onChanged();
        } else {
          e2Builder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .demo.Element2 e2 = 2;</code>
       */
      public Builder setE2(
          int index, org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2.Builder builderForValue) {
        if (e2Builder_ == null) {
          ensureE2IsMutable();
          e2_.set(index, builderForValue.build());
          onChanged();
        } else {
          e2Builder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .demo.Element2 e2 = 2;</code>
       */
      public Builder addE2(org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2 value) {
        if (e2Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureE2IsMutable();
          e2_.add(value);
          onChanged();
        } else {
          e2Builder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .demo.Element2 e2 = 2;</code>
       */
      public Builder addE2(
          int index, org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2 value) {
        if (e2Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureE2IsMutable();
          e2_.add(index, value);
          onChanged();
        } else {
          e2Builder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .demo.Element2 e2 = 2;</code>
       */
      public Builder addE2(
          org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2.Builder builderForValue) {
        if (e2Builder_ == null) {
          ensureE2IsMutable();
          e2_.add(builderForValue.build());
          onChanged();
        } else {
          e2Builder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .demo.Element2 e2 = 2;</code>
       */
      public Builder addE2(
          int index, org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2.Builder builderForValue) {
        if (e2Builder_ == null) {
          ensureE2IsMutable();
          e2_.add(index, builderForValue.build());
          onChanged();
        } else {
          e2Builder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .demo.Element2 e2 = 2;</code>
       */
      public Builder addAllE2(
          java.lang.Iterable<? extends org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2> values) {
        if (e2Builder_ == null) {
          ensureE2IsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, e2_);
          onChanged();
        } else {
          e2Builder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .demo.Element2 e2 = 2;</code>
       */
      public Builder clearE2() {
        if (e2Builder_ == null) {
          e2_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          e2Builder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .demo.Element2 e2 = 2;</code>
       */
      public Builder removeE2(int index) {
        if (e2Builder_ == null) {
          ensureE2IsMutable();
          e2_.remove(index);
          onChanged();
        } else {
          e2Builder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .demo.Element2 e2 = 2;</code>
       */
      public org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2.Builder getE2Builder(
          int index) {
        return getE2FieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .demo.Element2 e2 = 2;</code>
       */
      public org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2OrBuilder getE2OrBuilder(
          int index) {
        if (e2Builder_ == null) {
          return e2_.get(index);  } else {
          return e2Builder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .demo.Element2 e2 = 2;</code>
       */
      public java.util.List<? extends org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2OrBuilder> 
           getE2OrBuilderList() {
        if (e2Builder_ != null) {
          return e2Builder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(e2_);
        }
      }
      /**
       * <code>repeated .demo.Element2 e2 = 2;</code>
       */
      public org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2.Builder addE2Builder() {
        return getE2FieldBuilder().addBuilder(
            org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2.getDefaultInstance());
      }
      /**
       * <code>repeated .demo.Element2 e2 = 2;</code>
       */
      public org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2.Builder addE2Builder(
          int index) {
        return getE2FieldBuilder().addBuilder(
            index, org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2.getDefaultInstance());
      }
      /**
       * <code>repeated .demo.Element2 e2 = 2;</code>
       */
      public java.util.List<org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2.Builder> 
           getE2BuilderList() {
        return getE2FieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2, org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2.Builder, org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2OrBuilder> 
          getE2FieldBuilder() {
        if (e2Builder_ == null) {
          e2Builder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2, org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2.Builder, org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2OrBuilder>(
                  e2_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          e2_ = null;
        }
        return e2Builder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:demo.Element1)
    }

    // @@protoc_insertion_point(class_scope:demo.Element1)
    private static final org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1();
    }

    public static org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Element1>
        PARSER = new com.google.protobuf.AbstractParser<Element1>() {
      public Element1 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Element1(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Element1> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Element1> getParserForType() {
      return PARSER;
    }

    public org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element1 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface Element2OrBuilder extends
      // @@protoc_insertion_point(interface_extends:demo.Element2)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string grade = 2;</code>
     */
    java.lang.String getGrade();
    /**
     * <code>string grade = 2;</code>
     */
    com.google.protobuf.ByteString
        getGradeBytes();
  }
  /**
   * Protobuf type {@code demo.Element2}
   */
  public  static final class Element2 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:demo.Element2)
      Element2OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Element2.newBuilder() to construct.
    private Element2(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Element2() {
      name_ = "";
      grade_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Element2(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              grade_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.modelmapper.protobuf.gh392.DestinationInstructionProto.internal_static_demo_Element2_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.modelmapper.protobuf.gh392.DestinationInstructionProto.internal_static_demo_Element2_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2.class, org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GRADE_FIELD_NUMBER = 2;
    private volatile java.lang.Object grade_;
    /**
     * <code>string grade = 2;</code>
     */
    public java.lang.String getGrade() {
      java.lang.Object ref = grade_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        grade_ = s;
        return s;
      }
    }
    /**
     * <code>string grade = 2;</code>
     */
    public com.google.protobuf.ByteString
        getGradeBytes() {
      java.lang.Object ref = grade_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        grade_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!getGradeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, grade_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (!getGradeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, grade_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2)) {
        return super.equals(obj);
      }
      org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2 other = (org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && getGrade()
          .equals(other.getGrade());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + GRADE_FIELD_NUMBER;
      hash = (53 * hash) + getGrade().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code demo.Element2}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:demo.Element2)
        org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.modelmapper.protobuf.gh392.DestinationInstructionProto.internal_static_demo_Element2_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.modelmapper.protobuf.gh392.DestinationInstructionProto.internal_static_demo_Element2_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2.class, org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2.Builder.class);
      }

      // Construct using org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        grade_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.modelmapper.protobuf.gh392.DestinationInstructionProto.internal_static_demo_Element2_descriptor;
      }

      public org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2 getDefaultInstanceForType() {
        return org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2.getDefaultInstance();
      }

      public org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2 build() {
        org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2 buildPartial() {
        org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2 result = new org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2(this);
        result.name_ = name_;
        result.grade_ = grade_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2) {
          return mergeFrom((org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2 other) {
        if (other == org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getGrade().isEmpty()) {
          grade_ = other.grade_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object grade_ = "";
      /**
       * <code>string grade = 2;</code>
       */
      public java.lang.String getGrade() {
        java.lang.Object ref = grade_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          grade_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string grade = 2;</code>
       */
      public com.google.protobuf.ByteString
          getGradeBytes() {
        java.lang.Object ref = grade_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          grade_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string grade = 2;</code>
       */
      public Builder setGrade(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        grade_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string grade = 2;</code>
       */
      public Builder clearGrade() {
        
        grade_ = getDefaultInstance().getGrade();
        onChanged();
        return this;
      }
      /**
       * <code>string grade = 2;</code>
       */
      public Builder setGradeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        grade_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:demo.Element2)
    }

    // @@protoc_insertion_point(class_scope:demo.Element2)
    private static final org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2();
    }

    public static org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Element2>
        PARSER = new com.google.protobuf.AbstractParser<Element2>() {
      public Element2 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Element2(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Element2> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Element2> getParserForType() {
      return PARSER;
    }

    public org.modelmapper.protobuf.gh392.DestinationInstructionProto.Element2 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_Destination_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_Destination_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_Element1_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_Element1_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_Element2_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_Element2_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013gh265.proto\022\004demo\"G\n\013Destination\022\014\n\004ty" +
      "pe\030\001 \001(\t\022\032\n\002e1\030\002 \003(\0132\016.demo.Element1\022\016\n\006" +
      "status\030\003 \001(\t\"&\n\010Element1\022\032\n\002e2\030\002 \003(\0132\016.d" +
      "emo.Element2\"\'\n\010Element2\022\014\n\004name\030\001 \001(\t\022\r" +
      "\n\005grade\030\002 \001(\tB=\n\036org.modelmapper.protobu" +
      "f.gh392B\033DestinationInstructionProtob\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_demo_Destination_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_demo_Destination_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_Destination_descriptor,
        new java.lang.String[] { "Type", "E1", "Status", });
    internal_static_demo_Element1_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_demo_Element1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_Element1_descriptor,
        new java.lang.String[] { "E2", });
    internal_static_demo_Element2_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_demo_Element2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_Element2_descriptor,
        new java.lang.String[] { "Name", "Grade", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
